import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService with ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  Locale _locale = const Locale('en');
  Locale get locale => _locale;

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'appearance': 'APPEARANCE',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'general': 'GENERAL',
      'language': 'Language',
      'downloads': 'DOWNLOADS',
      'wifi_only': 'Download over Wi-Fi only',
      'auto_update': 'Auto-update apps',
      'notifications_title': 'NOTIFICATIONS',
      'allow_notifications': 'Allow Notifications',
      'storage': 'STORAGE',
      'clear_cache': 'Clear cache',
      'clear_data': 'Clear data',
      'home': 'Home',
      'search': 'Search',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'apps': 'Apps',
      'games': 'Games',
      'for_you': 'For You',
      'top_rated': 'Top Rated',
      'install': 'Install',
      'open': 'Open',
      'no_apps': 'No apps available yet',
      'pull_to_refresh': 'Pull down to refresh',
      'featured_app': 'FEATURED APP',
      'browse_category': 'Browse by Category',
      'academic': 'Academic',
      'library': 'Library',
      'campus_services': 'Campus Services',
      'student_life': 'Student Life',
      'dining': 'Dining',
      'search_placeholder': 'Search apps & games',
      'trending': 'Trending',
      'no_favorites': 'No favorites yet',
      'my_favorites': 'My Favorites',
      'dev_portal': 'Developer Portal',
      'sign_out': 'Sign Out',
      'recent_updated': 'Recently Updated',
      'view_all': 'View All',
      'account': 'ACCOUNT',
      'preferences': 'PREFERENCES',
      'support': 'SUPPORT',
      'account_settings': 'Account Settings',
      'manage_apps': 'Manage Apps & Device',
      'bookmarks': 'Bookmarks',
      'payments': 'Payments',
      'help_feedback': 'Help & Feedback',
      'about': 'About',
      'access_denied': 'Access Denied',
      'something_wrong': 'Something went wrong',
      'profile_not_found': 'Profile Not Found',
      'profile_not_found_desc': "We couldn't find your profile in our database.",
      'sign_out_reconnect': 'Sign Out & Reconnect',
      'sign_out_try_again': 'Sign Out & Try Again',
      'stat_rating': 'RATING',
      'stat_reports': 'REPORTS',
      'stat_size': 'SIZE',
      'stat_category': 'CATEGORY',
      'downloading': 'Downloading...',
      'installing': 'Installing...',
      'reinstall': 'Reinstall',
      'bookmark_removed': 'Removed from bookmarks',
      'bookmark_added': 'Added to bookmarks',
      'bookmark_error': 'Failed to update bookmark.',
      'preview': 'Preview',
      'screenshots_soon': 'Screenshots Coming Soon',
      'about_app': 'About This App',
      'ratings_reviews': 'Ratings & Reviews',
      'write_review': 'Review',
      'out_of_5': 'out of 5',
      'no_reviews': 'No reviews yet for this version.',
      'notifications': 'Notifications',
      'notifications_failed': 'Failed to load notifications',
      'no_notifications': 'No notifications yet',
      'notifications_desc': 'Important alerts and updates will appear here.',
      'time_now': 'now',
      'time_m_ago': 'm ago',
      'time_h_ago': 'h ago',
      'time_d_ago': 'd ago',
      'personal_info': 'PERSONAL INFORMATION',
      'first_name': 'First Name',
      'middle_initial': 'Middle Initial',
      'last_name': 'Last Name',
      'college_label': 'College',
      'course_label': 'Course',
      'change_photo': 'Change Profile Photo',
      'security': 'SECURITY',
      'change_password': 'Change Password',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'profile_updated': 'Profile updated successfully!',
      'wifi_only_error': 'Wi-Fi Only: Please connect to Wi-Fi to download.',
      'edit_review': 'Edit Review',
    },
    'tl': {
      'settings': 'Mga Setting',
      'appearance': 'ANYO',
      'theme': 'Tema',
      'light': 'Maliwanag',
      'dark': 'Madilim',
      'general': 'PAKALAHATAN',
      'language': 'Wika',
      'downloads': 'MGA DOWNLOAD',
      'wifi_only': 'I-download sa Wi-Fi lamang',
      'auto_update': 'Awtomatikong i-update',
      'notifications_title': 'MGA NOTIPIKASYON',
      'allow_notifications': 'Payagan ang mga Notipikasyon',
      'storage': 'IMBAKAN',
      'clear_cache': 'Linisin ang cache',
      'clear_data': 'Linisin ang data',
      'home': 'Home',
      'search': 'Maghanap',
      'favorites': 'Mga Paborito',
      'profile': 'Profile',
      'apps': 'Mga App',
      'games': 'Mga Laro',
      'for_you': 'Para sa Iyo',
      'top_rated': 'Pinaka-Rated',
      'install': 'I-install',
      'open': 'Buksan',
      'no_apps': 'Wala pang mga app',
      'pull_to_refresh': 'Hilahin pababa para i-refresh',
      'featured_app': 'Tampok na App',
      'browse_category': 'Mag-browse ayon sa Kategorya',
      'academic': 'Akademiko',
      'library': 'Aklatan',
      'campus_services': 'Serbisyo sa Kampus',
      'student_life': 'Buhay Estudyante',
      'dining': 'Kainan',
      'search_placeholder': 'Maghanap ng mga app at laro',
      'trending': 'Trending',
      'no_favorites': 'Wala pang mga paborito',
      'my_favorites': 'Aking mga Paborito',
      'dev_portal': 'Portal ng Developer',
      'sign_out': 'Mag-sign Out',
      'recent_updated': 'Kamakailang Na-update',
      'view_all': 'Tingnan Lahat',
      'account': 'AKAWNT',
      'preferences': 'MGA PREPERENSYA',
      'support': 'SUPORTA',
      'account_settings': 'Mga Setting ng Akawnt',
      'manage_apps': 'Pamahalaan ang mga App at Device',
      'bookmarks': 'Mga Bookmark',
      'payments': 'Mga Pagbabayad',
      'help_feedback': 'Tulong at Feedback',
      'about': 'Tungkol Sa',
      'access_denied': 'Tinanggihan ang Akses',
      'something_wrong': 'May mali sa nangyari',
      'profile_not_found': 'Hindi Nahanap ang Profile',
      'profile_not_found_desc': "Hindi namin nahanap ang iyong profile sa aming database.",
      'sign_out_reconnect': 'Mag-sign Out at Kumonekta muli',
      'sign_out_try_again': 'Mag-sign Out at Subukang muli',
      'stat_rating': 'RATING',
      'stat_reports': 'MGA ULAT',
      'stat_size': 'LAKI',
      'stat_category': 'KATEGORYA',
      'downloading': 'Nag-o-download...',
      'installing': 'Nag-i-install...',
      'reinstall': 'I-reinstall',
      'bookmark_removed': 'Inalis sa mga bookmark',
      'bookmark_added': 'Idinagdag sa mga bookmark',
      'bookmark_error': 'Bigo sa pag-update ng bookmark.',
      'preview': 'Preview',
      'screenshots_soon': 'Screenshots Malapit Na',
      'about_app': 'Tungkol sa App na Ito',
      'ratings_reviews': 'Ratings at Reviews',
      'write_review': 'Review',
      'out_of_5': 'mula sa 5',
      'no_reviews': 'Wala pang mga review para sa bersyong ito.',
      'notifications': 'Mga Notipikasyon',
      'notifications_failed': 'Bigo sa pag-load ng mga notipikasyon',
      'no_notifications': 'Wala pang mga notipikasyon',
      'notifications_desc': 'Ang mga mahahalagang alerto at update ay lilitaw dito.',
      'time_now': 'ngayon',
      'time_m_ago': 'min nakalipas',
      'time_h_ago': 'oras nakalipas',
      'time_d_ago': 'araw nakalipas',
      'personal_info': 'MAKATAONG IMPORMASYON',
      'first_name': 'Unang Pangalan',
      'middle_initial': 'Inisyal ng Gitna',
      'last_name': 'Huling Pangalan',
      'college_label': 'Kolehiyo',
      'course_label': 'Kurso',
      'change_photo': 'Baguhin ang Larawan ng Profile',
      'security': 'SEGURIDAD',
      'change_password': 'Baguhin ang Password',
      'save_changes': 'I-save ang mga Pagbabago',
      'cancel': 'Kanselahin',
      'profile_updated': 'Matagumpay na na-update ang Profile!',
      'wifi_only_error': 'Wi-Fi Lamang: Mangyaring kumonekta sa Wi-Fi upang mag-download.',
      'edit_review': 'I-edit ang Review',
    },
  };

  String translate(String key) {
    return _localizedValues[_locale.languageCode]?[key] ?? key;
  }

  String get currentLanguageName {
    return _locale.languageCode == 'en' ? 'English' : 'Filipino';
  }

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString('languageCode') ?? 'en';
    _locale = Locale(langCode);
    notifyListeners();
  }

  Future<void> setLanguage(String langCode) async {
    _locale = Locale(langCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('languageCode', langCode);
    notifyListeners();
  }
}
